---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Build Dockerfile
    command: docker build -t addressbook:ansible .
  - name: run Image
    command: docker run -itd -P addressbook:ansible
