---- 

- hosts: webservers
  become: true
  become_user: root

  tasks: 
  - name: install tomcat
    yum:
      name: tomcat
      state: present
  - name: start tomcat
    service:
      name: tomcat 
      state: started
