---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    yum: name=git state=present
  - name: copy address book
    copy: src="/var/lib/jenkins/workspace/Build Pipeline/target/addressbook.war" dest=/tmp/Addressbook/
  - name: Build Dockerfile
    command: chdir=/tmp/Addressbook docker build -t addressbook:ansible .
  - name: run Image
    command: docker run -itd -P addressbook:ansible
